import { AlertTriangle } from 'lucide-react'
import { DATA_MODE } from '../../core/config'

export function DisclosureBanner() {
  return (
    <div className="border-b border-wait/30 bg-wait/10">
      <div className="mx-auto flex max-w-7xl items-start gap-3 px-4 py-3 text-sm text-wait sm:px-6">
        <AlertTriangle className="mt-0.5 h-4 w-4 shrink-0" />
        <p>
          <strong>{DATA_MODE === 'SIMULATED' ? 'Simulated demo data.' : 'Live market data.'}</strong>{' '}
          {DATA_MODE === 'SIMULATED'
            ? 'All prices, charts, and signals on this page are generated by a mock strategy for educational purposes only. Nothing here is financial advice, and no signal is a guarantee of future results.'
            : 'Prices are live, but signals remain for educational purposes only. Nothing here is financial advice, and no signal is a guarantee of future results.'}
        </p>
      </div>
    </div>
  )
}
